title: Mingeon's Blog
author: Mingeon Kim
email: mingeon.dev@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Mingeon's Blog
  tagline: 배운 것을 내 언어로 정리하기
  date_format: "%b %-d, %Y"
  style: blue
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    github: mingeon-dev

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

url: "https://mingeon-dev.github.io/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-feed
